USE [NFMT_User]
GO

SET IDENTITY_INSERT [dbo].[Corporation] ON
INSERT [dbo].[Corporation] ([CorpId], [ParentId], [CorpCode], [CorpName], [CorpEName], [TaxPayerId], [CorpFullName], [CorpFullEName], [CorpAddress], [CorpEAddress], [CorpTel], [CorpFax], [CorpZip], [CorpType], [IsSelf], [CorpStatus], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (2, 1, N'shanghai maike', N'上海迈科金属资源有限公司', N'shanghai maike corp', N'1', N'上海迈科金属资源有限公司', N'shanghai maike corp', N'上海市浦东新区世纪大道1501号SOHO世纪广场27楼', N'27th Floor, 1501 Century Boulevard, Shanghai Pudong New Area, SOHO Century Plaza', N'+86-(0)21-5085-6688', N'+86-(0)21-5085-2099', N'200122', 119, 1, 50, 1, CAST(0x0000A34E00F84069 AS DateTime), 1, CAST(0x0000A36900B8FE80 AS DateTime))
INSERT [dbo].[Corporation] ([CorpId], [ParentId], [CorpCode], [CorpName], [CorpEName], [TaxPayerId], [CorpFullName], [CorpFullEName], [CorpAddress], [CorpEAddress], [CorpTel], [CorpFax], [CorpZip], [CorpType], [IsSelf], [CorpStatus], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (5, 1, NULL, N'西安迈科金属有限公司', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 119, 1, 50, 1, CAST(0x0000A35C01018235 AS DateTime), NULL, NULL)
INSERT [dbo].[Corporation] ([CorpId], [ParentId], [CorpCode], [CorpName], [CorpEName], [TaxPayerId], [CorpFullName], [CorpFullEName], [CorpAddress], [CorpEAddress], [CorpTel], [CorpFax], [CorpZip], [CorpType], [IsSelf], [CorpStatus], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (6, 1, NULL, N'香港裕明贸易有限公司', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 119, 1, 50, 1, CAST(0x0000A35C0101BAA5 AS DateTime), NULL, NULL)
INSERT [dbo].[Corporation] ([CorpId], [ParentId], [CorpCode], [CorpName], [CorpEName], [TaxPayerId], [CorpFullName], [CorpFullEName], [CorpAddress], [CorpEAddress], [CorpTel], [CorpFax], [CorpZip], [CorpType], [IsSelf], [CorpStatus], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (7, 1, NULL, N'香港迈迪信投资有限公司', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 119, 1, 50, 1, CAST(0x0000A35C0101BAA5 AS DateTime), NULL, NULL)
INSERT [dbo].[Corporation] ([CorpId], [ParentId], [CorpCode], [CorpName], [CorpEName], [TaxPayerId], [CorpFullName], [CorpFullEName], [CorpAddress], [CorpEAddress], [CorpTel], [CorpFax], [CorpZip], [CorpType], [IsSelf], [CorpStatus], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (8, 1, NULL, N'深圳迈科资源有限公司', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 119, 1, 50, 1, CAST(0x0000A35C0101BAA6 AS DateTime), NULL, NULL)
INSERT [dbo].[Corporation] ([CorpId], [ParentId], [CorpCode], [CorpName], [CorpEName], [TaxPayerId], [CorpFullName], [CorpFullEName], [CorpAddress], [CorpEAddress], [CorpTel], [CorpFax], [CorpZip], [CorpType], [IsSelf], [CorpStatus], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (9, 1, N'A001', N'上海迪亮', N'2', N'2', N'上海迪亮', N'SHANGHAI DI LIANG ', N'SOHO', N'SOHO', N'12345678', N'12345678', N'200133', 120, 1, 50, 1, CAST(0x0000A361010FA79B AS DateTime), 1, CAST(0x0000A36900B9449E AS DateTime))
INSERT [dbo].[Corporation] ([CorpId], [ParentId], [CorpCode], [CorpName], [CorpEName], [TaxPayerId], [CorpFullName], [CorpFullEName], [CorpAddress], [CorpEAddress], [CorpTel], [CorpFax], [CorpZip], [CorpType], [IsSelf], [CorpStatus], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (10, 2, N'QDOM001', N'青岛欧美公司001', N'QDOMC001', N'58421222', N'青岛欧美公司001', N'QDOMC001', N'山东省青岛市', N'SHANDONGQINGDAO', NULL, NULL, NULL, 119, 0, 50, 1, CAST(0x0000A36900B87FF1 AS DateTime), 1, CAST(0x0000A36900B87FF1 AS DateTime))
INSERT [dbo].[Corporation] ([CorpId], [ParentId], [CorpCode], [CorpName], [CorpEName], [TaxPayerId], [CorpFullName], [CorpFullEName], [CorpAddress], [CorpEAddress], [CorpTel], [CorpFax], [CorpZip], [CorpType], [IsSelf], [CorpStatus], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (11, 3, N'DFIFD', N'上海金川有限公司', N'JCCORP', N'22646546', N'上海金川有限公司', N'上海金川有限公司', N'上海金川有限公司', N'上海金川有限公司', N'上海金川有限公司', N'上海金川有限公司', N'上海金川有限公司', 119, 0, 50, 1, CAST(0x0000A37100B0CD87 AS DateTime), 1, CAST(0x0000A37100B0CD87 AS DateTime))
INSERT [dbo].[Corporation] ([CorpId], [ParentId], [CorpCode], [CorpName], [CorpEName], [TaxPayerId], [CorpFullName], [CorpFullEName], [CorpAddress], [CorpEAddress], [CorpTel], [CorpFax], [CorpZip], [CorpType], [IsSelf], [CorpStatus], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (12, 2, N'fDIP', N'欧美1号', N'欧美1号', N'432423', N'欧美1号', N'欧美1号', N'欧美1号', N'欧美1号', N'欧美1号', N'欧美1号', N'欧美1号', 119, 0, 50, 1, CAST(0x0000A37100B1335A AS DateTime), 1, CAST(0x0000A37100B1335A AS DateTime))
INSERT [dbo].[Corporation] ([CorpId], [ParentId], [CorpCode], [CorpName], [CorpEName], [TaxPayerId], [CorpFullName], [CorpFullEName], [CorpAddress], [CorpEAddress], [CorpTel], [CorpFax], [CorpZip], [CorpType], [IsSelf], [CorpStatus], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (13, 1, N'迈科1', N'迈科1', N'迈科1', N'231123', N'迈科1', N'迈科1', N'迈科1', N'迈科1', N'迈科1', N'迈科1', N'迈科1', 119, 1, 60, 1, CAST(0x0000A37100BA7535 AS DateTime), 1, CAST(0x0000A3A9009D9479 AS DateTime))
INSERT [dbo].[Corporation] ([CorpId], [ParentId], [CorpCode], [CorpName], [CorpEName], [TaxPayerId], [CorpFullName], [CorpFullEName], [CorpAddress], [CorpEAddress], [CorpTel], [CorpFax], [CorpZip], [CorpType], [IsSelf], [CorpStatus], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (14, 1, N'迈科2', N'迈科2', N'迈科2', N'43423', N'迈科2', N'迈科2', N'迈科2', N'迈科2', N'迈科2', N'迈科2', N'迈科2', 119, 1, 60, 1, CAST(0x0000A37100BA85B2 AS DateTime), 1, CAST(0x0000A3A9009D8AA5 AS DateTime))
INSERT [dbo].[Corporation] ([CorpId], [ParentId], [CorpCode], [CorpName], [CorpEName], [TaxPayerId], [CorpFullName], [CorpFullEName], [CorpAddress], [CorpEAddress], [CorpTel], [CorpFax], [CorpZip], [CorpType], [IsSelf], [CorpStatus], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (15, 1, N'迈科3', N'迈科3', N'迈科3', N'234234', N'迈科3', N'迈科3', N'迈科3', N'迈科3', N'迈科3', N'迈科3', N'迈科3', 119, 1, 60, 1, CAST(0x0000A37100BA96B5 AS DateTime), 1, CAST(0x0000A3A9009D80E1 AS DateTime))
INSERT [dbo].[Corporation] ([CorpId], [ParentId], [CorpCode], [CorpName], [CorpEName], [TaxPayerId], [CorpFullName], [CorpFullEName], [CorpAddress], [CorpEAddress], [CorpTel], [CorpFax], [CorpZip], [CorpType], [IsSelf], [CorpStatus], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (16, 1, N'Gtest1', N'Gtest2', N'Gtest3', N'11022023302', N'Gtest4', N'Gtest5', N'Gtest6', N'Gtest7', N'Gtest8', N'Gtest9', N'Gtest10', 120, 1, 60, 1, CAST(0x0000A37101023CFF AS DateTime), 1, CAST(0x0000A3A9009E294C AS DateTime))
INSERT [dbo].[Corporation] ([CorpId], [ParentId], [CorpCode], [CorpName], [CorpEName], [TaxPayerId], [CorpFullName], [CorpFullEName], [CorpAddress], [CorpEAddress], [CorpTel], [CorpFax], [CorpZip], [CorpType], [IsSelf], [CorpStatus], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (17, 14, N'新加坡加能可', N'新加坡加能可', N'新加坡加能可', N'0264646', N'新加坡加能可', N'新加坡加能可', N'新加坡加能可', N'新加坡加能可', N'64565', N'234234', N'2342', 119, 0, 50, 1, CAST(0x0000A3A20115A663 AS DateTime), 1, CAST(0x0000A3A20115A663 AS DateTime))
INSERT [dbo].[Corporation] ([CorpId], [ParentId], [CorpCode], [CorpName], [CorpEName], [TaxPayerId], [CorpFullName], [CorpFullEName], [CorpAddress], [CorpEAddress], [CorpTel], [CorpFax], [CorpZip], [CorpType], [IsSelf], [CorpStatus], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (18, 14, N'台湾加能可', N'台湾加能可', N'台湾加能可', N'213123', N'台湾加能可', N'台湾加能可', N'台湾加能可', N'台湾加能可', N'342', N'234', N'234', 119, 0, 50, 1, CAST(0x0000A3A20115CABA AS DateTime), 1, CAST(0x0000A3A20115CABA AS DateTime))
INSERT [dbo].[Corporation] ([CorpId], [ParentId], [CorpCode], [CorpName], [CorpEName], [TaxPayerId], [CorpFullName], [CorpFullEName], [CorpAddress], [CorpEAddress], [CorpTel], [CorpFax], [CorpZip], [CorpType], [IsSelf], [CorpStatus], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (21, 3, N'211', N'211', N'211', N'111', N'111', N'111', N'111', N'111', N'111', N'111', N'111', 120, 0, 60, 1, CAST(0x0000A3A8011DB55D AS DateTime), 1, CAST(0x0000A3A9009D6924 AS DateTime))
INSERT [dbo].[Corporation] ([CorpId], [ParentId], [CorpCode], [CorpName], [CorpEName], [TaxPayerId], [CorpFullName], [CorpFullEName], [CorpAddress], [CorpEAddress], [CorpTel], [CorpFax], [CorpZip], [CorpType], [IsSelf], [CorpStatus], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (23, 3, N'1', N'1', N'1', N'1', N'1', N'1', N'1', N'1', N'1', N'1', N'1', 120, 0, 60, 1, CAST(0x0000A3A9009DF3C0 AS DateTime), 1, CAST(0x0000A3B000ABF734 AS DateTime))
INSERT [dbo].[Corporation] ([CorpId], [ParentId], [CorpCode], [CorpName], [CorpEName], [TaxPayerId], [CorpFullName], [CorpFullEName], [CorpAddress], [CorpEAddress], [CorpTel], [CorpFax], [CorpZip], [CorpType], [IsSelf], [CorpStatus], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (24, 1, N'12', N'3', N'3', N'1', N'1', N'1', N'7', N'1', N'1', N'1', N'8', 119, 1, 1, 1, CAST(0x0000A3A900A2BC4C AS DateTime), 1, CAST(0x0000A3AF00EFA12B AS DateTime))
SET IDENTITY_INSERT [dbo].[Corporation] OFF