USE [NFMT_User]
GO

SET IDENTITY_INSERT [dbo].[Department] ON
INSERT [dbo].[Department] ([DeptId], [CorpId], [DeptCode], [DeptName], [DeptFullName], [DeptShort], [DeptType], [ParentLeve], [DeptStatus], [DeptLevel], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (1, 2, N'IT', N'信息技术部', N'信息技术部', N'IT', 36, 0, 50, 2, 1, CAST(0x0000A34E00F8C50F AS DateTime), NULL, NULL)
INSERT [dbo].[Department] ([DeptId], [CorpId], [DeptCode], [DeptName], [DeptFullName], [DeptShort], [DeptType], [ParentLeve], [DeptStatus], [DeptLevel], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (2, 2, N'FundsCenter', N'财管中心', N'财管中心', N'FundsCenter', 36, 0, 50, 2, 1, CAST(0x0000A354009C2F3A AS DateTime), NULL, NULL)
INSERT [dbo].[Department] ([DeptId], [CorpId], [DeptCode], [DeptName], [DeptFullName], [DeptShort], [DeptType], [ParentLeve], [DeptStatus], [DeptLevel], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (3, 2, NULL, N'采购部', NULL, NULL, 36, 0, 50, 2, 1, CAST(0x0000A35C01031C5B AS DateTime), NULL, NULL)
INSERT [dbo].[Department] ([DeptId], [CorpId], [DeptCode], [DeptName], [DeptFullName], [DeptShort], [DeptType], [ParentLeve], [DeptStatus], [DeptLevel], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (4, 2, NULL, N'外贸铜营销部', NULL, NULL, 36, 0, 50, 2, 1, CAST(0x0000A35C01039F43 AS DateTime), NULL, NULL)
INSERT [dbo].[Department] ([DeptId], [CorpId], [DeptCode], [DeptName], [DeptFullName], [DeptShort], [DeptType], [ParentLeve], [DeptStatus], [DeptLevel], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (5, 2, NULL, N'内贸铜营销部', NULL, NULL, 35, 0, 50, 2, 1, CAST(0x0000A35C01039F43 AS DateTime), NULL, NULL)
INSERT [dbo].[Department] ([DeptId], [CorpId], [DeptCode], [DeptName], [DeptFullName], [DeptShort], [DeptType], [ParentLeve], [DeptStatus], [DeptLevel], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (6, 2, NULL, N'价格中心', NULL, NULL, 35, 0, 50, 2, 1, CAST(0x0000A35C01039F43 AS DateTime), NULL, NULL)
INSERT [dbo].[Department] ([DeptId], [CorpId], [DeptCode], [DeptName], [DeptFullName], [DeptShort], [DeptType], [ParentLeve], [DeptStatus], [DeptLevel], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (7, 2, NULL, N'上海分公司财务部', NULL, NULL, 35, 0, 50, 2, 1, CAST(0x0000A35C01039F43 AS DateTime), NULL, NULL)
INSERT [dbo].[Department] ([DeptId], [CorpId], [DeptCode], [DeptName], [DeptFullName], [DeptShort], [DeptType], [ParentLeve], [DeptStatus], [DeptLevel], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (8, 2, NULL, N'仓储部', NULL, NULL, 35, 0, 50, 2, 1, CAST(0x0000A35C01039F44 AS DateTime), 1, CAST(0x0000A3A900A6C4EF AS DateTime))
INSERT [dbo].[Department] ([DeptId], [CorpId], [DeptCode], [DeptName], [DeptFullName], [DeptShort], [DeptType], [ParentLeve], [DeptStatus], [DeptLevel], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (9, 2, N'测试组1', N'测试组1', N'测试组1', N'测试组1', 36, 0, 50, 3, 1, CAST(0x0000A36200B7B524 AS DateTime), 1, CAST(0x0000A3AF00EFEDD0 AS DateTime))
INSERT [dbo].[Department] ([DeptId], [CorpId], [DeptCode], [DeptName], [DeptFullName], [DeptShort], [DeptType], [ParentLeve], [DeptStatus], [DeptLevel], [CreatorId], [CreateTime], [LastModifyId], [LastModifyTime]) VALUES (10, 2, N'2', N'2', N'2', N'2', 36, 2, 1, 3, 1, CAST(0x0000A3A900A0D0FC AS DateTime), 1, CAST(0x0000A3A900A6B60C AS DateTime))
SET IDENTITY_INSERT [dbo].[Department] OFF