//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Data.Entity;

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apply
    {
        [Key]
        public int ApplyId { get; set; }
        public string ApplyNo { get; set; }
        public Nullable<int> ApplyType { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<System.DateTime> ApplyTime { get; set; }
        public Nullable<int> ApplyStatus { get; set; }
        public Nullable<int> ApplyDept { get; set; }
        public Nullable<int> ApplyCorp { get; set; }
        public string ApplyDesc { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
