//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attach
    {
        public int AttachId { get; set; }
        public string AttachName { get; set; }
        public string ServerAttachName { get; set; }
        public string AttachExt { get; set; }
        public Nullable<int> AttachType { get; set; }
        public string AttachInfo { get; set; }
        public Nullable<int> AttachLength { get; set; }
        public string AttachPath { get; set; }
        public Nullable<int> AttachStatus { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
