//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Con_Summary
    {
        public int SummaryId { get; set; }
        public Nullable<int> SummaryApplyId { get; set; }
        public Nullable<System.DateTime> SummaryDate { get; set; }
        public Nullable<int> SummaryEmpId { get; set; }
        public string Meno { get; set; }
        public Nullable<int> SummaryStatus { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
