//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Con_SummaryApply
    {
        public int SummaryApplyId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<int> SubId { get; set; }
        public Nullable<int> SAType { get; set; }
        public Nullable<System.DateTime> SADate { get; set; }
        public Nullable<int> ApplyDept { get; set; }
        public Nullable<int> BuyerCorp { get; set; }
        public string BuyerAddress { get; set; }
        public Nullable<int> PaymentStyle { get; set; }
        public Nullable<int> RecBankId { get; set; }
        public Nullable<int> OutPricOption { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string BankCode { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<int> Curency { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Bala { get; set; }
        public string Meno { get; set; }
        public Nullable<int> SAStatus { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
