//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Con_Lc
    {
        public int LcId { get; set; }
        public Nullable<int> IssueBank { get; set; }
        public Nullable<int> AdviseBank { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<int> FutureDay { get; set; }
        public Nullable<decimal> LcBala { get; set; }
        public Nullable<int> Currency { get; set; }
        public Nullable<int> LCStatus { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
