//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Con_Contract
    {
        public int ContractId { get; set; }
        public string ContractNo { get; set; }
        public string OutContractNo { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public string ContractName { get; set; }
        public Nullable<int> TradeBorder { get; set; }
        public Nullable<int> ContractLimit { get; set; }
        public Nullable<int> ContractSide { get; set; }
        public Nullable<int> TradeDirection { get; set; }
        public Nullable<int> HaveGoodsFlow { get; set; }
        public Nullable<System.DateTime> ContractPeriodS { get; set; }
        public Nullable<System.DateTime> ContractPeriodE { get; set; }
        public Nullable<decimal> Premium { get; set; }
        public Nullable<System.DateTime> InitQP { get; set; }
        public Nullable<int> AssetId { get; set; }
        public Nullable<int> SettleCurrency { get; set; }
        public Nullable<decimal> SignAmount { get; set; }
        public Nullable<decimal> ExeAmount { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> PriceMode { get; set; }
        public string Memo { get; set; }
        public Nullable<int> DeliveryStyle { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> CreateFrom { get; set; }
        public Nullable<int> ContractStatus { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
