//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Con_ContractDetail
    {
        public int ContractDetailId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<int> DiscountBase { get; set; }
        public Nullable<int> DiscountType { get; set; }
        public Nullable<decimal> DiscountRate { get; set; }
        public Nullable<int> DelayType { get; set; }
        public Nullable<decimal> DelayRate { get; set; }
        public Nullable<decimal> MoreOrLess { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
