//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Con_ContractSubQP
    {
        public int QPId { get; set; }
        public Nullable<int> SubId { get; set; }
        public Nullable<int> CurQP { get; set; }
        public decimal InitAmount { get; set; }
        public decimal ChgedAmount { get; set; }
        public int QPChgDate { get; set; }
        public int QPFrom { get; set; }
        public decimal ThisQPFeeBala { get; set; }
        public string QPMemo { get; set; }
        public decimal TotalInitFeeBala { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
