//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Con_SubPrice
    {
        public int SubPriceId { get; set; }
        public Nullable<int> SubId { get; set; }
        public Nullable<decimal> FixedPrice { get; set; }
        public string FixedPriceMemo { get; set; }
        public Nullable<int> WhoDoPrice { get; set; }
        public Nullable<decimal> AlmostPrice { get; set; }
        public Nullable<System.DateTime> DoPriceBeginDate { get; set; }
        public Nullable<System.DateTime> DoPriceEndDate { get; set; }
        public Nullable<bool> IsQP { get; set; }
        public Nullable<int> PriceFrom { get; set; }
        public Nullable<int> PriceStyle1 { get; set; }
        public Nullable<int> PriceStyle2 { get; set; }
        public Nullable<int> MarginMode { get; set; }
        public Nullable<decimal> MarginAmount { get; set; }
        public string MarginMemo { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
