//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doc_DocumentOrder
    {
        public int OrderId { get; set; }
        public string OrderNo { get; set; }
        public Nullable<int> CommercialId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public string ContractNo { get; set; }
        public Nullable<int> SubId { get; set; }
        public Nullable<int> LCId { get; set; }
        public string LCNo { get; set; }
        public Nullable<int> LCDay { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> ApplyCorp { get; set; }
        public Nullable<int> ApplyDept { get; set; }
        public Nullable<int> SellerCorp { get; set; }
        public Nullable<int> BuyerCorp { get; set; }
        public string BuyerCorpName { get; set; }
        public string BuyerAddress { get; set; }
        public Nullable<int> PaymentStyle { get; set; }
        public Nullable<int> RecBankId { get; set; }
        public string DiscountBase { get; set; }
        public Nullable<int> AssetId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string AreaName { get; set; }
        public string BankCode { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> Currency { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> InvBala { get; set; }
        public Nullable<decimal> InvGap { get; set; }
        public Nullable<int> Bundles { get; set; }
        public string Meno { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<int> ApplyEmpId { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
