//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doc_DocumentOrderDetail
    {
        public int DetailId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> InvoiceCopies { get; set; }
        public string InvoiceSpecific { get; set; }
        public Nullable<int> QualityCopies { get; set; }
        public string QualitySpecific { get; set; }
        public Nullable<int> WeightCopies { get; set; }
        public string WeightSpecific { get; set; }
        public Nullable<int> TexCopies { get; set; }
        public string TexSpecific { get; set; }
        public Nullable<int> DeliverCopies { get; set; }
        public string DeliverSpecific { get; set; }
        public Nullable<int> TotalInvCopies { get; set; }
        public string TotalInvSpecific { get; set; }
        public Nullable<int> DetailStatus { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
