//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doc_DocumentStock
    {
        public int DetailId { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> OrderStockDetailId { get; set; }
        public Nullable<int> StockId { get; set; }
        public Nullable<int> StockNameId { get; set; }
        public string RefNo { get; set; }
        public Nullable<int> DetailStatus { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
