//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fun_Funds
    {
        public int FundsId { get; set; }
        public Nullable<int> FundsLimitd { get; set; }
        public Nullable<int> BlocId { get; set; }
        public Nullable<int> CorpId { get; set; }
        public Nullable<decimal> FundsValue { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> FundsType { get; set; }
    }
}
