//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fun_Receivable
    {
        public int ReceivableId { get; set; }
        public Nullable<int> ReceiveEmpId { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<int> ReceivableGroupId { get; set; }
        public Nullable<int> ReceivableCorpId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> PayBala { get; set; }
        public Nullable<int> ReceivableBank { get; set; }
        public Nullable<int> ReceivableAccoontId { get; set; }
        public Nullable<int> PayGroupId { get; set; }
        public Nullable<int> PayCorpId { get; set; }
        public string PayCorpName { get; set; }
        public Nullable<int> PayBankId { get; set; }
        public string PayBank { get; set; }
        public Nullable<int> PayAccountId { get; set; }
        public string PayAccount { get; set; }
        public string PayWord { get; set; }
        public string BankLog { get; set; }
        public Nullable<int> ReceiveStatus { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
