//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fun_PaymentVirtual
    {
        public int VirtualId { get; set; }
        public int PaymentId { get; set; }
        public Nullable<int> PayApplyId { get; set; }
        public Nullable<decimal> PayBala { get; set; }
        public Nullable<int> DetailStatus { get; set; }
        public Nullable<bool> IsConfirm { get; set; }
        public string Memo { get; set; }
        public string ConfirmMemo { get; set; }
        public Nullable<int> FundsLogId { get; set; }
    }
}
