//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fun_FundsLog
    {
        public int FundsLogId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<int> SubId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<int> InBlocId { get; set; }
        public Nullable<int> InCorpId { get; set; }
        public Nullable<int> InBankId { get; set; }
        public Nullable<int> InAccountId { get; set; }
        public Nullable<int> OutBlocId { get; set; }
        public Nullable<int> OutCorpId { get; set; }
        public Nullable<int> OutBankId { get; set; }
        public string OutBank { get; set; }
        public Nullable<int> OutAccountId { get; set; }
        public string OutAccount { get; set; }
        public Nullable<decimal> FundsBala { get; set; }
        public Nullable<int> FundsType { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> LogDirection { get; set; }
        public int LogType { get; set; }
        public Nullable<int> PayMode { get; set; }
        public Nullable<bool> IsVirtualPay { get; set; }
        public string FundsDesc { get; set; }
        public Nullable<int> OpPerson { get; set; }
        public string LogSourceBase { get; set; }
        public string LogSource { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<int> LogStatus { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
