//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fun_CashIn
    {
        public int CashInId { get; set; }
        public Nullable<int> CashInEmpId { get; set; }
        public Nullable<System.DateTime> CashInDate { get; set; }
        public Nullable<int> CashInBlocId { get; set; }
        public Nullable<int> CashInCorpId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> CashInBala { get; set; }
        public Nullable<int> CashInBank { get; set; }
        public Nullable<int> CashInAccoontId { get; set; }
        public Nullable<int> CashInMode { get; set; }
        public Nullable<int> PayBlocId { get; set; }
        public Nullable<int> PayCorpId { get; set; }
        public string PayCorpName { get; set; }
        public Nullable<int> PayBankId { get; set; }
        public string PayBank { get; set; }
        public Nullable<int> PayAccountId { get; set; }
        public string PayAccount { get; set; }
        public string PayWord { get; set; }
        public string BankLog { get; set; }
        public Nullable<int> CashInStatus { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
