//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fun_CashInContract_Ref
    {
        public int RefId { get; set; }
        public Nullable<int> CorpRefId { get; set; }
        public Nullable<int> AllotId { get; set; }
        public Nullable<int> CashInId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<int> SubContractId { get; set; }
        public Nullable<decimal> AllotBala { get; set; }
        public Nullable<int> DetailStatus { get; set; }
        public Nullable<int> FundsLogId { get; set; }
    }
}
