//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fun_PaymentContractDetail
    {
        public int DetailId { get; set; }
        public int PaymentId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<int> ContractSubId { get; set; }
        public Nullable<int> PayApplyId { get; set; }
        public Nullable<int> PayApplyDetailId { get; set; }
        public Nullable<decimal> PayBala { get; set; }
        public Nullable<decimal> FundsBala { get; set; }
        public Nullable<decimal> VirtualBala { get; set; }
    }
}
