//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fun_StockPayApply_Ref
    {
        public int RefId { get; set; }
        public Nullable<int> PayApplyId { get; set; }
        public Nullable<int> ContractRefId { get; set; }
        public Nullable<int> StockId { get; set; }
        public Nullable<int> StockLogId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<int> SubId { get; set; }
        public Nullable<decimal> ApplyBala { get; set; }
        public Nullable<int> RefStatus { get; set; }
    }
}
