//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fun_PayApply
    {
        public int PayApplyId { get; set; }
        public Nullable<int> ApplyId { get; set; }
        public Nullable<int> PayApplySource { get; set; }
        public Nullable<int> RecBlocId { get; set; }
        public Nullable<int> RecCorpId { get; set; }
        public Nullable<int> RecBankId { get; set; }
        public Nullable<int> RecBankAccountId { get; set; }
        public string RecBankAccount { get; set; }
        public Nullable<decimal> ApplyBala { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> PayMode { get; set; }
        public Nullable<System.DateTime> PayDeadline { get; set; }
        public string SpecialDesc { get; set; }
        public Nullable<int> PayMatter { get; set; }
        public Nullable<int> RealPayCorpId { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
