//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fun_ReceivableAllot
    {
        public int ReceivableAllotId { get; set; }
        public Nullable<decimal> AllotBala { get; set; }
        public Nullable<int> AllotType { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public string AllotDesc { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<System.DateTime> AllotTime { get; set; }
        public Nullable<int> AllotStatus { get; set; }
        public Nullable<int> AllotFrom { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
