//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_InvoiceApplyDetail
    {
        public int DetailId { get; set; }
        public Nullable<int> InvoiceApplyId { get; set; }
        public Nullable<int> ApplyId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<int> BussinessInvoiceId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<int> SubContractId { get; set; }
        public Nullable<int> StockLogId { get; set; }
        public Nullable<decimal> InvoicePrice { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<decimal> InterestAmount { get; set; }
        public Nullable<decimal> OtherAmount { get; set; }
        public Nullable<decimal> InvoiceBala { get; set; }
        public Nullable<int> DetailStatus { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
