//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_BusinessInvoice
    {
        public int BusinessInvoiceId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<int> RefInvoiceId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<int> SubContractId { get; set; }
        public Nullable<int> AssetId { get; set; }
        public Nullable<decimal> IntegerAmount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> MUId { get; set; }
        public Nullable<decimal> MarginRatio { get; set; }
        public Nullable<decimal> VATRatio { get; set; }
        public Nullable<decimal> VATBala { get; set; }
    }
}
