//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_BusinessInvoiceDetail
    {
        public int DetailId { get; set; }
        public Nullable<int> BusinessInvoiceId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<int> RefDetailId { get; set; }
        public Nullable<int> StockId { get; set; }
        public Nullable<int> StockLogId { get; set; }
        public Nullable<int> ConfirmPriceId { get; set; }
        public Nullable<int> ConfirmDetailId { get; set; }
        public Nullable<int> PricingId { get; set; }
        public Nullable<int> PricingDetailId { get; set; }
        public Nullable<int> FeeType { get; set; }
        public Nullable<decimal> IntegerAmount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> CalculateDay { get; set; }
        public Nullable<decimal> Bala { get; set; }
        public Nullable<int> DetailStatus { get; set; }
    }
}
