//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pri_PriceConfirmDetail
    {
        public int DetailId { get; set; }
        public Nullable<int> PriceConfirmId { get; set; }
        public Nullable<int> InterestDetailId { get; set; }
        public Nullable<int> InterestId { get; set; }
        public Nullable<int> StockLogId { get; set; }
        public Nullable<int> StockId { get; set; }
        public Nullable<decimal> ConfirmAmount { get; set; }
        public Nullable<decimal> SettlePrice { get; set; }
        public Nullable<decimal> SettleBala { get; set; }
        public Nullable<int> DetailStatus { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
