//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pri_Pricing
    {
        public int PricingId { get; set; }
        public Nullable<int> PricingApplyId { get; set; }
        public Nullable<decimal> PricingWeight { get; set; }
        public Nullable<int> MUId { get; set; }
        public Nullable<int> ExchangeId { get; set; }
        public Nullable<int> FuturesCodeId { get; set; }
        public Nullable<System.DateTime> FuturesCodeEndDate { get; set; }
        public Nullable<System.DateTime> SpotQP { get; set; }
        public Nullable<decimal> DelayFee { get; set; }
        public Nullable<decimal> Spread { get; set; }
        public Nullable<decimal> OtherFee { get; set; }
        public Nullable<decimal> AvgPrice { get; set; }
        public Nullable<System.DateTime> PricingTime { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> Pricinger { get; set; }
        public Nullable<int> AssertId { get; set; }
        public Nullable<int> PricingDirection { get; set; }
        public Nullable<int> PricingStatus { get; set; }
        public Nullable<decimal> FinalPrice { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
