//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pri_PricingPerson
    {
        public int PersoinId { get; set; }
        public Nullable<int> BlocId { get; set; }
        public Nullable<int> CorpId { get; set; }
        public string PricingName { get; set; }
        public string Job { get; set; }
        public string PricingPhone { get; set; }
        public string Phone2 { get; set; }
        public Nullable<int> PersoinStatus { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
