//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pri_PricingApply
    {
        public int PricingApplyId { get; set; }
        public Nullable<int> ApplyId { get; set; }
        public Nullable<int> SubContractId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<int> PricingDirection { get; set; }
        public Nullable<System.DateTime> QPDate { get; set; }
        public Nullable<decimal> DelayAmount { get; set; }
        public Nullable<decimal> DelayFee { get; set; }
        public Nullable<System.DateTime> DelayQPDate { get; set; }
        public Nullable<decimal> OtherFee { get; set; }
        public string OtherDesc { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
        public Nullable<decimal> MaxPrice { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> PricingBlocId { get; set; }
        public Nullable<int> PricingCorpId { get; set; }
        public Nullable<decimal> PricingWeight { get; set; }
        public Nullable<int> MUId { get; set; }
        public Nullable<int> AssertId { get; set; }
        public Nullable<int> PricingPersoinId { get; set; }
        public Nullable<int> PricingStyle { get; set; }
        public Nullable<System.DateTime> DeclareDate { get; set; }
        public Nullable<System.DateTime> AvgPriceStart { get; set; }
        public Nullable<System.DateTime> AvgPriceEnd { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
