//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pri_StopLossDetail
    {
        public int DetailId { get; set; }
        public Nullable<int> StopLossId { get; set; }
        public Nullable<int> StopLossApplyId { get; set; }
        public Nullable<int> StopLossApplyDetailId { get; set; }
        public Nullable<int> StockId { get; set; }
        public Nullable<int> StockLogId { get; set; }
        public Nullable<decimal> StopLossWeight { get; set; }
        public Nullable<decimal> AvgPrice { get; set; }
        public Nullable<System.DateTime> StopLossTime { get; set; }
        public Nullable<int> StopLosser { get; set; }
        public Nullable<int> DetailStatus { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
