//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pri_StopLossApply
    {
        public int StopLossApplyId { get; set; }
        public Nullable<int> ApplyId { get; set; }
        public Nullable<int> PricingId { get; set; }
        public Nullable<int> PricingDirection { get; set; }
        public Nullable<int> SubContractId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<int> AssertId { get; set; }
        public Nullable<decimal> StopLossPrice { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> StopLossWeight { get; set; }
        public Nullable<int> MUId { get; set; }
    }
}
