//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pri_PriceConfirm
    {
        public int PriceConfirmId { get; set; }
        public Nullable<int> OutCorpId { get; set; }
        public Nullable<int> InCorpId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<int> SubId { get; set; }
        public Nullable<decimal> ContractAmount { get; set; }
        public Nullable<decimal> SubAmount { get; set; }
        public Nullable<decimal> RealityAmount { get; set; }
        public Nullable<decimal> PricingAvg { get; set; }
        public Nullable<decimal> PremiumAvg { get; set; }
        public Nullable<decimal> InterestAvg { get; set; }
        public Nullable<decimal> OtherAvg { get; set; }
        public Nullable<decimal> InterestBala { get; set; }
        public Nullable<decimal> SettlePrice { get; set; }
        public Nullable<decimal> SettleBala { get; set; }
        public Nullable<System.DateTime> PricingDate { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> TakeCorpId { get; set; }
        public string ContactPerson { get; set; }
        public string Memo { get; set; }
        public Nullable<int> PriceConfirmStatus { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
