//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pri_Interest
    {
        public int InterestId { get; set; }
        public Nullable<int> SubContractId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> PricingUnit { get; set; }
        public Nullable<decimal> Premium { get; set; }
        public Nullable<decimal> OtherPrice { get; set; }
        public Nullable<decimal> InterestPrice { get; set; }
        public Nullable<decimal> PayCapital { get; set; }
        public Nullable<decimal> CurCapital { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public Nullable<decimal> InterestBala { get; set; }
        public Nullable<decimal> InterestAmountDay { get; set; }
        public Nullable<decimal> InterestAmount { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> InterestStyle { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> InterestDate { get; set; }
        public Nullable<int> InterestStatus { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
