//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rep_ClientCurrent
    {
        public int CurId { get; set; }
        public Nullable<int> InBlocId { get; set; }
        public Nullable<int> InCorpId { get; set; }
        public Nullable<int> OutBlocId { get; set; }
        public Nullable<int> OutCorpId { get; set; }
        public Nullable<System.DateTime> CurDate { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> CashInBala { get; set; }
        public Nullable<decimal> CashOutBala { get; set; }
        public Nullable<decimal> InvoiceOutBala { get; set; }
        public Nullable<decimal> InvoiceInBala { get; set; }
        public Nullable<int> CurStatus { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
