//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class St_CustomsClearance
    {
        public int CustomsId { get; set; }
        public Nullable<int> CustomsApplyId { get; set; }
        public Nullable<int> Customser { get; set; }
        public Nullable<int> CustomsCorpId { get; set; }
        public Nullable<System.DateTime> CustomsDate { get; set; }
        public Nullable<int> CustomsName { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> CustomsPrice { get; set; }
        public Nullable<decimal> TariffRate { get; set; }
        public Nullable<decimal> AddedValueRate { get; set; }
        public Nullable<decimal> OtherFees { get; set; }
        public string Memo { get; set; }
        public Nullable<int> CustomsStatus { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
