//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class St_Pledge
    {
        public int PledgeId { get; set; }
        public Nullable<int> PledgeApplyId { get; set; }
        public Nullable<int> Pledger { get; set; }
        public Nullable<System.DateTime> PledgeTime { get; set; }
        public Nullable<int> PledgeBank { get; set; }
        public string Memo { get; set; }
        public Nullable<int> PledgeStatus { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
