//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class St_PledgeDetial
    {
        public int DetailId { get; set; }
        public Nullable<int> PledgeId { get; set; }
        public Nullable<int> DetailStatus { get; set; }
        public Nullable<int> PledgeApplyDetailId { get; set; }
        public Nullable<int> StockId { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<decimal> PledgePrice { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> StockLogId { get; set; }
    }
}
