//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class St_StockLog
    {
        public int StockLogId { get; set; }
        public Nullable<int> StockId { get; set; }
        public Nullable<int> StockNameId { get; set; }
        public string RefNo { get; set; }
        public Nullable<int> LogDirection { get; set; }
        public int LogType { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<int> SubContractId { get; set; }
        public System.DateTime LogDate { get; set; }
        public Nullable<int> OpPerson { get; set; }
        public Nullable<int> AssetId { get; set; }
        public int Bundles { get; set; }
        public decimal GrossAmount { get; set; }
        public decimal NetAmount { get; set; }
        public Nullable<decimal> GapAmount { get; set; }
        public Nullable<int> MUId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> CorpId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> CustomsType { get; set; }
        public Nullable<int> DeliverPlaceId { get; set; }
        public Nullable<int> ProducerId { get; set; }
        public string PaperNo { get; set; }
        public Nullable<int> PaperHolder { get; set; }
        public string CardNo { get; set; }
        public Nullable<int> StockType { get; set; }
        public string Format { get; set; }
        public Nullable<int> OriginPlaceId { get; set; }
        public string OriginPlace { get; set; }
        public string Memo { get; set; }
        public Nullable<int> LogStatus { get; set; }
        public string LogSourceBase { get; set; }
        public string LogSource { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
