//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class St_StockOut
    {
        public int StockOutId { get; set; }
        public Nullable<int> StockOutApplyId { get; set; }
        public Nullable<int> Executor { get; set; }
        public Nullable<int> Confirmor { get; set; }
        public Nullable<System.DateTime> StockOutTime { get; set; }
        public Nullable<decimal> GrosstAmount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<int> Bundles { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> StockOperateType { get; set; }
        public string Memo { get; set; }
        public Nullable<int> StockOutStatus { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
