//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class St_SplitDocStock_Ref
    {
        public int RefId { get; set; }
        public Nullable<int> SplitDocDetailId { get; set; }
        public Nullable<int> NewRefNoId { get; set; }
        public Nullable<int> NewStockId { get; set; }
        public Nullable<int> OldRefNoId { get; set; }
        public Nullable<int> OldStockId { get; set; }
        public Nullable<int> RefStatus { get; set; }
    }
}
