//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class St_Stock
    {
        public int StockId { get; set; }
        public Nullable<int> StockNameId { get; set; }
        public string StockNo { get; set; }
        public Nullable<System.DateTime> StockDate { get; set; }
        public Nullable<int> AssetId { get; set; }
        public Nullable<int> Bundles { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<decimal> ReceiptInGap { get; set; }
        public Nullable<decimal> ReceiptOutGap { get; set; }
        public Nullable<decimal> CurGrossAmount { get; set; }
        public Nullable<decimal> CurNetAmount { get; set; }
        public Nullable<int> UintId { get; set; }
        public Nullable<int> DeliverPlaceId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> CustomsType { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> CorpId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> ProducerId { get; set; }
        public string PaperNo { get; set; }
        public Nullable<int> PaperHolder { get; set; }
        public string Format { get; set; }
        public Nullable<int> OriginPlaceId { get; set; }
        public string OriginPlace { get; set; }
        public Nullable<int> PreStatus { get; set; }
        public Nullable<int> StockStatus { get; set; }
        public string CardNo { get; set; }
        public string Memo { get; set; }
        public Nullable<int> StockType { get; set; }
    }
}
