//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class St_SplitDoc
    {
        public int SplitDocId { get; set; }
        public Nullable<int> Spliter { get; set; }
        public Nullable<System.DateTime> SplitDocTime { get; set; }
        public Nullable<int> SplitDocStatus { get; set; }
        public Nullable<int> OldRefNoId { get; set; }
        public string OldRefNo { get; set; }
        public Nullable<int> OldStockId { get; set; }
        public Nullable<int> StockLogId { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
