//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class St_SplitDocDetail
    {
        public int DetailId { get; set; }
        public Nullable<int> SplitDocId { get; set; }
        public Nullable<int> DetailStatus { get; set; }
        public string NewRefNo { get; set; }
        public Nullable<int> OldRefNoId { get; set; }
        public Nullable<int> OldStockId { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> AssetId { get; set; }
        public Nullable<int> Bundles { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string PaperNo { get; set; }
        public Nullable<int> PaperHolder { get; set; }
        public string CardNo { get; set; }
        public Nullable<int> StockLogId { get; set; }
        public string Memo { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
