//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMTSite_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class St_StockOutApply
    {
        public int StockOutApplyId { get; set; }
        public Nullable<int> ApplyId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<int> SubContractId { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<int> Bundles { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> BuyCorpId { get; set; }
        public Nullable<int> CreateFrom { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
