truncate table dbo.Apply
truncate table dbo.Attach
truncate table dbo.Con_Contract
truncate table dbo.Con_ContractAttach
truncate table dbo.Con_ContractCorporationDetail
truncate table dbo.Con_ContractDept
truncate table dbo.Con_ContractDetail
truncate table dbo.Con_ContractPrice
truncate table dbo.Con_ContractSub
truncate table dbo.Con_ContractSubAttach
truncate table dbo.Con_Lc
truncate table dbo.Con_LcAttach
truncate table dbo.Con_Premium
truncate table dbo.Con_SubCorporationDetail
truncate table dbo.Con_SubDetail
truncate table dbo.Con_SubPrice
truncate table dbo.Doc_Document
truncate table dbo.Doc_DocumentInvoice
truncate table dbo.Doc_DocumentOrder
truncate table dbo.Doc_DocumentOrderAttach
truncate table dbo.Doc_DocumentOrderDetail
truncate table dbo.Doc_DocumentOrderInvoice
truncate table dbo.Doc_DocumentOrderStock
truncate table dbo.Doc_DocumentStock
truncate table dbo.Fun_CashIn
truncate table dbo.Fun_CashInAllot
truncate table dbo.Fun_CashInAttach
truncate table dbo.Fun_CashInContract_Ref
truncate table dbo.Fun_CashInCorp_Ref
truncate table dbo.Fun_CashInInvoice_Ref
truncate table dbo.Fun_CashInStcok_Ref
truncate table dbo.Fun_ContractFundsAllotStock_Ref
truncate table dbo.Fun_ContractPayApply_Ref
truncate table dbo.Fun_ContractReceivable_Ref
truncate table dbo.Fun_CorpFundsAllotContract_Ref
truncate table dbo.Fun_CorpFundsAllotStock_Ref
truncate table dbo.Fun_FundsLog
truncate table dbo.Fun_FundsLogAttach
truncate table dbo.Fun_InvoicePayApply_Ref
truncate table dbo.Fun_PayApply
truncate table dbo.Fun_PayApplyAttach
truncate table dbo.Fun_Payment
truncate table dbo.Fun_PaymentAttach
truncate table dbo.Fun_PaymentContractDetail
truncate table dbo.Fun_PaymentInvioceDetail
truncate table dbo.Fun_PaymentStockDetail
truncate table dbo.Fun_PaymentVirtual
truncate table dbo.Fun_StockPayApply_Ref
truncate table dbo.Inv_BusinessInvoice
truncate table dbo.Inv_BusinessInvoiceDetail
truncate table dbo.Inv_FinanceBusinessInvoice_Ref
truncate table dbo.Inv_FinanceInvoice
truncate table dbo.Inv_FinanceInvoiceDetail
truncate table dbo.Inv_FinBusInvAllot
truncate table dbo.Inv_FinBusInvAllotDetail
truncate table dbo.Inv_SI
truncate table dbo.Inv_SIDetail
truncate table dbo.Invoice
truncate table dbo.InvoiceAttach
truncate table dbo.Pri_Pricing
truncate table dbo.Pri_PricingApply
truncate table dbo.Pri_PricingApplyDelay
truncate table dbo.Pri_PricingApplyDetail
truncate table dbo.Pri_PricingDetail
truncate table dbo.Pri_PricingPerson
truncate table dbo.Pri_StopLoss
truncate table dbo.Pri_StopLossApply
truncate table dbo.Pri_StopLossApplyDetail
truncate table dbo.Pri_StopLossDetail
truncate table dbo.St_ContractStockIn_Ref
truncate table dbo.St_CustomsApplyAttach
truncate table dbo.St_CustomsApplyDetail
truncate table dbo.St_CustomsAttach
truncate table dbo.St_CustomsClearance
truncate table dbo.St_CustomsClearanceApply
truncate table dbo.St_CustomsDetail
truncate table dbo.St_Pledge
truncate table dbo.St_PledgeApply
truncate table dbo.St_PledgeApplyAttach
truncate table dbo.St_PledgeApplyDetail
truncate table dbo.St_PledgeAttach
truncate table dbo.St_PledgeDetial
truncate table dbo.St_Repo
truncate table dbo.St_RepoApply
truncate table dbo.St_RepoApplyAttach
truncate table dbo.St_RepoApplyDetail
truncate table dbo.St_RepoAttach
truncate table dbo.St_RepoDetail
truncate table dbo.St_SplitDoc
truncate table dbo.St_SplitDocAttach
truncate table dbo.St_SplitDocDetail
truncate table dbo.St_SplitDocStock_Ref
truncate table dbo.St_Stock
truncate table dbo.St_StockExclusive
truncate table dbo.St_StockIn
truncate table dbo.St_StockInAttach
truncate table dbo.St_StockInStock_Ref
truncate table dbo.St_StockLog
truncate table dbo.St_StockLogAttach
truncate table dbo.St_StockMove
truncate table dbo.St_StockMoveApply
truncate table dbo.St_StockMoveApplyAttach
truncate table dbo.St_StockMoveApplyDetail
truncate table dbo.St_StockMoveAttach
truncate table dbo.St_StockMoveDetail
truncate table dbo.St_StockName
truncate table dbo.St_StockOut
truncate table dbo.St_StockOutApply
truncate table dbo.St_StockOutApplyAttach
truncate table dbo.St_StockOutApplyDetail
truncate table dbo.St_StockOutAttach
truncate table dbo.St_StockOutDetail
truncate table dbo.St_StockReceipt
truncate table dbo.St_StockReceiptDetail
truncate table dbo.St_StocktAttach