USE [NFMT_WorkFlow]
GO
SET IDENTITY_INSERT [dbo].[Wf_Node] ON
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (1, 1, 50, N'部门经理审核', 1, 1, 0, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (2, 1, 50, N'总经理审核', 1, 0, 0, 1, 2, 2, 2)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (3, 1, 50, N'总裁审核', 1, 0, 1, 2, 3, 3, 3)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (4, 1, 50, N'VP审核', 1, 0, 0, 3, 1, 1, 2)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (5, 2, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (7, 3, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (10, 4, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (12, 6, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (14, 7, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (16, 8, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (17, 9, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (18, 10, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (20, 11, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (21, 12, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (22, 13, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (23, 14, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (25, 15, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (26, 16, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (27, 17, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (28, 18, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (29, 19, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (30, 20, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (31, 21, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (32, 22, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (33, 23, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (34, 24, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (35, 25, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (36, 26, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (37, 27, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (38, 28, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (39, 29, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
INSERT [dbo].[Wf_Node] ([NodeId], [MasterId], [NodeStatus], [NodeName], [NodeType], [IsFirst], [IsLast], [PreNodeId], [RoleId], [AuthGroupId], [NodeLevel]) VALUES (40, 30, 50, N'管理员审核', 1, 1, 1, 0, 1, 1, 1)
SET IDENTITY_INSERT [dbo].[Wf_Node] OFF